const options = {
    colors: [
        { "value": "Red", "hex": '#a30c0c' },
        { "value": "Blue", "hex": '#3993DD' },
        { "value": "Green", "hex": '#09814A' },
        { "value": "Yellow", "hex": '#FBB13C' },
        { "value": "Orange", "hex": '#DC602E' },
        { "value": "Tan", "hex": '#BEA57D' },
        { "value": "White", "hex": '#ffffff' },
        { "value": "Black", "hex": '#071013' },
        { "value": "Grey", "hex": '#7D7A79' },
        { "value": "Silver", "hex": '#CFCBCA' },
        { "value": "Brown", "hex": '#663825' },
        { "value": "Purple", "hex": '#613F75' },
        { "value": "Pink", "hex": '#EF798A' },
        { "value": "Navy", "hex": '#0B132B' }
    ],
    times: ["10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM","6:00 PM", "8:00 PM"],
    types: [{
        "name": "All Season",
        "desc": "Go all year long with the most durable tires on the market"
    },
    {
        "name": "Performance",
        "desc": "The best tire for getting the best use out of your tires."
    },
    {
        "name": "Winter",
        "desc": "The best tires for rough climates. Stay safe on your northern roads"
    }
    ],
    amounts: [1, 2, 3, 4, 5, 6, 7, 8],
    icons: ['directions_car', 'build', 'straighten' , 'palette',
        'money', 'home', 'today', 'schedule', 'local_mall', 'drag_indicator'],
    extras: ['BYD',
        'Brilliance',
        'Changan',
        'Chery',
        'Citroen',
        'Daewoo',
        'Daihatsu',
        'Datsun',
        'Dongfeng',
        'FAW',
        'GAZ',
        'Geely',
        'Great Wall',
        'Haval',
        'Holden',
        'IVECO',
        'Lancia',
        'Lifan',
        'MG',
        'Marussia',
        'Opel',
        'Peugeot',
        'Ravon',
        'Renault',
        'Seat',
        'Skoda',
        'Ssang Yong',
        'UAZ',
        'VAZ'],
    years: [
        1990,
        1991,
        1992,
        1993,
        1994,
        1995,
        1996,
        1997,
        1998,
        1999,
        2000,
        2001,
        2002,
        2003,
        2004,
        2005,
        2006,
        2007,
        2008,
        2009,
        2010,
        2011,
        2012,
        2013,
        2014,
        2015,
        2016,
        2017,
        2018,
        2019,
        2020
    ]
}

export { options };


