version: 0.1

phases:
 install:
    run-as: Linux-user-name
    runtime-versions:
      runtime: nodejs 8
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      - echo building...
      - ng build 
#       - scp -i ./tires_key_pair.pem -r **/* ubuntu@ec2-35-183-165-236.ca-central-1.compute.amazonaws.com:/opt/front-end
# artifacts:
#     files:
#       - "**/*"
#   discard-paths: no
#   base-directory: dist/tires-in-time-angular